"""
88_seed_transfers.py — Seed ~200 curated transfer records into the transfers table.

Seeds the transfers table with real transfers from:
- Summer 2022 window
- January 2023 window
- Summer 2023 window
- Summer 2024 window
- January 2025 window
- Summer 2025 window
- January 2026 window

Attempts to link player_id by matching player_name against people.name.
Computes age_at_transfer from people.date_of_birth when matched.
Looks up primary_archetype from player_profiles.earned_archetype.
Sets source='seed' and confidence='high' on every row.

Requires: migration 045 (transfers table)

Usage:
    python 88_seed_transfers.py --dry-run     # preview
    python 88_seed_transfers.py               # insert/upsert
    python 88_seed_transfers.py --force       # delete existing seed data first
"""
import argparse
import sys
from datetime import date

import psycopg2
from psycopg2.extras import RealDictCursor

from config import POSTGRES_DSN

parser = argparse.ArgumentParser(description="Seed transfer records")
parser.add_argument("--dry-run", action="store_true")
parser.add_argument("--force", action="store_true")
args = parser.parse_args()

if not POSTGRES_DSN:
    print("ERROR: Set POSTGRES_DSN in .env.local")
    sys.exit(1)

conn = psycopg2.connect(POSTGRES_DSN)
conn.autocommit = True
cur = conn.cursor()

# ── Transfer data ────────────────────────────────────────────────────────────

TRANSFERS = [
    # ── Summer 2022 window ───────────────────────────────────────────────────
    {
        "player_name": "Erling Haaland",
        "from_club": "Borussia Dortmund", "from_league": "Bundesliga",
        "to_club": "Manchester City", "to_league": "Premier League",
        "fee_eur_m": 60, "fee_type": "permanent",
        "deal_context": "release_clause",
        "position": "CF", "transfer_date": "2022-07-01",
        "transfer_window": "2022_summer",
        "notes": "€60m release clause. 86 goals in 89 BVB apps. Generational striker signing.",
    },
    {
        "player_name": "Aurélien Tchouaméni",
        "from_club": "AS Monaco", "from_league": "Ligue 1",
        "to_club": "Real Madrid", "to_league": "La Liga",
        "fee_eur_m": 80, "fee_type": "permanent",
        "deal_context": "club_decision",
        "position": "DM", "transfer_date": "2022-06-14",
        "transfer_window": "2022_summer",
        "notes": "Beat Liverpool and PSG to sign. Long-term Casemiro replacement.",
    },
    {
        "player_name": "Darwin Núñez",
        "from_club": "Benfica", "from_league": "Primeira Liga",
        "to_club": "Liverpool", "to_league": "Premier League",
        "fee_eur_m": 75, "fee_type": "permanent",
        "deal_context": "club_decision",
        "position": "CF", "transfer_date": "2022-06-14",
        "transfer_window": "2022_summer",
        "notes": "€75m initial, up to €100m with add-ons. Mané replacement.",
    },
    {
        "player_name": "Wesley Fofana",
        "from_club": "Leicester City", "from_league": "Premier League",
        "to_club": "Chelsea", "to_league": "Premier League",
        "fee_eur_m": 80, "fee_type": "permanent",
        "deal_context": "club_decision",
        "position": "CD", "transfer_date": "2022-08-31",
        "transfer_window": "2022_summer",
        "notes": "Third most expensive defender ever at the time. Deadline day.",
    },
    {
        "player_name": "Casemiro",
        "from_club": "Real Madrid", "from_league": "La Liga",
        "to_club": "Manchester United", "to_league": "Premier League",
        "fee_eur_m": 70, "fee_type": "permanent",
        "deal_context": "club_decision",
        "position": "DM", "transfer_date": "2022-08-22",
        "transfer_window": "2022_summer",
        "notes": "Left Madrid after 9 years and 5 Champions League titles.",
    },
    {
        "player_name": "Marc Cucurella",
        "from_club": "Brighton", "from_league": "Premier League",
        "to_club": "Chelsea", "to_league": "Premier League",
        "fee_eur_m": 65, "fee_type": "permanent",
        "deal_context": "club_decision",
        "position": "WD", "transfer_date": "2022-08-05",
        "transfer_window": "2022_summer",
        "notes": "Chelsea's Boehly-era spending spree. One season at Brighton.",
    },
    {
        "player_name": "Alexander Isak",
        "from_club": "Real Sociedad", "from_league": "La Liga",
        "to_club": "Newcastle United", "to_league": "Premier League",
        "fee_eur_m": 63, "fee_type": "permanent",
        "deal_context": "club_decision",
        "position": "CF", "transfer_date": "2022-08-26",
        "transfer_window": "2022_summer",
        "notes": "Newcastle club record. PIF-era marquee signing.",
    },
    {
        "player_name": "Richarlison",
        "from_club": "Everton", "from_league": "Premier League",
        "to_club": "Tottenham Hotspur", "to_league": "Premier League",
        "fee_eur_m": 58, "fee_type": "permanent",
        "deal_context": "club_decision",
        "position": "CF", "transfer_date": "2022-07-01",
        "transfer_window": "2022_summer",
        "notes": "€58m plus add-ons. Conte wanted a versatile forward.",
    },
    {
        "player_name": "Lisandro Martínez",
        "from_club": "Ajax", "from_league": "Eredivisie",
        "to_club": "Manchester United", "to_league": "Premier League",
        "fee_eur_m": 57, "fee_type": "permanent",
        "deal_context": "club_decision",
        "position": "CD", "transfer_date": "2022-07-27",
        "transfer_window": "2022_summer",
        "notes": "Ten Hag reunion signing. Nicknamed 'The Butcher'.",
    },
    {
        "player_name": "Raheem Sterling",
        "from_club": "Manchester City", "from_league": "Premier League",
        "to_club": "Chelsea", "to_league": "Premier League",
        "fee_eur_m": 50, "fee_type": "permanent",
        "deal_context": "club_decision",
        "position": "WF", "transfer_date": "2022-07-13",
        "transfer_window": "2022_summer",
        "notes": "First Boehly-era Chelsea signing. Wanted guaranteed starting role.",
    },
    {
        "player_name": "Gabriel Jesus",
        "from_club": "Manchester City", "from_league": "Premier League",
        "to_club": "Arsenal", "to_league": "Premier League",
        "fee_eur_m": 45, "fee_type": "permanent",
        "deal_context": "club_decision",
        "position": "CF", "transfer_date": "2022-07-04",
        "transfer_window": "2022_summer",
        "notes": "Arteta's key summer signing. Transformed Arsenal's attack early on.",
    },
    {
        "player_name": "Kalvin Phillips",
        "from_club": "Leeds United", "from_league": "Premier League",
        "to_club": "Manchester City", "to_league": "Premier League",
        "fee_eur_m": 45, "fee_type": "permanent",
        "deal_context": "club_decision",
        "position": "DM", "transfer_date": "2022-07-04",
        "transfer_window": "2022_summer",
        "notes": "England international. Struggled for minutes behind Rodri.",
    },
    {
        "player_name": "Sven Botman",
        "from_club": "Lille", "from_league": "Ligue 1",
        "to_club": "Newcastle United", "to_league": "Premier League",
        "fee_eur_m": 37, "fee_type": "permanent",
        "deal_context": "club_decision",
        "position": "CD", "transfer_date": "2022-07-01",
        "transfer_window": "2022_summer",
        "notes": "Dutch CB from Lille. Key part of Newcastle's defensive improvement.",
    },
    {
        "player_name": "Oleksandr Zinchenko",
        "from_club": "Manchester City", "from_league": "Premier League",
        "to_club": "Arsenal", "to_league": "Premier League",
        "fee_eur_m": 32, "fee_type": "permanent",
        "deal_context": "club_decision",
        "position": "WD", "transfer_date": "2022-07-22",
        "transfer_window": "2022_summer",
        "notes": "Arteta reunion. Inverted full-back role pioneer at Arsenal.",
    },
    {
        "player_name": "Brenden Aaronson",
        "from_club": "Red Bull Salzburg", "from_league": "Austrian Bundesliga",
        "to_club": "Leeds United", "to_league": "Premier League",
        "fee_eur_m": 30, "fee_type": "permanent",
        "deal_context": "club_decision",
        "position": "AM", "transfer_date": "2022-05-26",
        "transfer_window": "2022_summer",
        "notes": "American international. Early deal agreed. Went down with Leeds.",
    },
    {
        "player_name": "Tyler Adams",
        "from_club": "RB Leipzig", "from_league": "Bundesliga",
        "to_club": "Leeds United", "to_league": "Premier League",
        "fee_eur_m": 20, "fee_type": "permanent",
        "deal_context": "club_decision",
        "position": "CM", "transfer_date": "2022-07-06",
        "transfer_window": "2022_summer",
        "notes": "Jesse Marsch reunion. USMNT captain.",
    },
    {
        "player_name": "Kalidou Koulibaly",
        "from_club": "Napoli", "from_league": "Serie A",
        "to_club": "Chelsea", "to_league": "Premier League",
        "fee_eur_m": 38, "fee_type": "permanent",
        "deal_context": "club_decision",
        "position": "CD", "transfer_date": "2022-07-16",
        "transfer_window": "2022_summer",
        "notes": "8 years at Napoli. Chelsea signed him at 31. Left after one season.",
    },
    {
        "player_name": "Sadio Mané",
        "from_club": "Liverpool", "from_league": "Premier League",
        "to_club": "Bayern Munich", "to_league": "Bundesliga",
        "fee_eur_m": 32, "fee_type": "permanent",
        "deal_context": "transfer_request",
        "position": "WF", "transfer_date": "2022-06-22",
        "transfer_window": "2022_summer",
        "notes": "Left Liverpool after 6 years. Wanted a new challenge. Bayern struggled with fit.",
    },
    {
        "player_name": "Fábio Vieira",
        "from_club": "Porto", "from_league": "Primeira Liga",
        "to_club": "Arsenal", "to_league": "Premier League",
        "fee_eur_m": 35, "fee_type": "permanent",
        "deal_context": "club_decision",
        "position": "AM", "transfer_date": "2022-06-30",
        "transfer_window": "2022_summer",
        "notes": "Portuguese playmaker. Struggled with injuries at Arsenal.",
    },
    {
        "player_name": "Matthijs de Ligt",
        "from_club": "Juventus", "from_league": "Serie A",
        "to_club": "Bayern Munich", "to_league": "Bundesliga",
        "fee_eur_m": 67, "fee_type": "permanent",
        "deal_context": "club_decision",
        "position": "CD", "transfer_date": "2022-07-19",
        "transfer_window": "2022_summer",
        "notes": "Left Juve after 3 years. Bayern's defensive rebuild under Nagelsmann.",
    },

    {
        "player_name": "Gianluca Scamacca",
        "from_club": "Sassuolo", "from_league": "Serie A",
        "to_club": "West Ham United", "to_league": "Premier League",
        "fee_eur_m": 36, "fee_type": "permanent",
        "deal_context": "club_decision",
        "position": "CF", "transfer_date": "2022-07-26",
        "transfer_window": "2022_summer",
        "notes": "Italian striker. Conference League winner at West Ham.",
    },
    {
        "player_name": "Robert Lewandowski",
        "from_club": "Bayern Munich", "from_league": "Bundesliga",
        "to_club": "Barcelona", "to_league": "La Liga",
        "fee_eur_m": 45, "fee_type": "permanent",
        "deal_context": "transfer_request",
        "position": "CF", "transfer_date": "2022-07-19",
        "transfer_window": "2022_summer",
        "notes": "Left Bayern after 8 seasons and 344 goals. Forced the move to Barcelona.",
    },

    # ── January 2023 window ──────────────────────────────────────────────────
    {
        "player_name": "Enzo Fernández",
        "from_club": "Benfica", "from_league": "Primeira Liga",
        "to_club": "Chelsea", "to_league": "Premier League",
        "fee_eur_m": 121, "fee_type": "permanent",
        "deal_context": "release_clause",
        "position": "CM", "transfer_date": "2023-01-31",
        "transfer_window": "2023_jan",
        "notes": "World Cup Golden Ball winner. British record fee. €121m release clause.",
    },
    {
        "player_name": "Mykhailo Mudryk",
        "from_club": "Shakhtar Donetsk", "from_league": "Ukrainian Premier League",
        "to_club": "Chelsea", "to_league": "Premier League",
        "fee_eur_m": 70, "fee_type": "permanent",
        "deal_context": "club_decision",
        "position": "WF", "transfer_date": "2023-01-15",
        "transfer_window": "2023_jan",
        "notes": "Chelsea hijacked Arsenal's deal. €70m initial plus €30m add-ons.",
    },
    {
        "player_name": "Cody Gakpo",
        "from_club": "PSV Eindhoven", "from_league": "Eredivisie",
        "to_club": "Liverpool", "to_league": "Premier League",
        "fee_eur_m": 42, "fee_type": "permanent",
        "deal_context": "club_decision",
        "position": "WF", "transfer_date": "2023-01-01",
        "transfer_window": "2023_jan",
        "notes": "Deal agreed before window opened. World Cup form sealed move.",
    },
    {
        "player_name": "Leandro Trossard",
        "from_club": "Brighton", "from_league": "Premier League",
        "to_club": "Arsenal", "to_league": "Premier League",
        "fee_eur_m": 27, "fee_type": "permanent",
        "deal_context": "transfer_request",
        "position": "WF", "transfer_date": "2023-01-20",
        "transfer_window": "2023_jan",
        "notes": "Fell out with De Zerbi. Arsenal got versatile forward depth.",
    },


    # ── Summer 2023 window ───────────────────────────────────────────────────
    {
        "player_name": "Declan Rice",
        "from_club": "West Ham United", "from_league": "Premier League",
        "to_club": "Arsenal", "to_league": "Premier League",
        "fee_eur_m": 116, "fee_type": "permanent",
        "deal_context": "club_decision",
        "position": "DM", "transfer_date": "2023-07-15",
        "transfer_window": "2023_summer",
        "notes": "Arsenal record. £105m. Conference League winner turned title challenger.",
    },
    {
        "player_name": "Moisés Caicedo",
        "from_club": "Brighton", "from_league": "Premier League",
        "to_club": "Chelsea", "to_league": "Premier League",
        "fee_eur_m": 115, "fee_type": "permanent",
        "deal_context": "club_decision",
        "position": "DM", "transfer_date": "2023-08-14",
        "transfer_window": "2023_summer",
        "notes": "PL record fee. Chelsea beat Liverpool in late bidding war.",
    },
    {
        "player_name": "Jude Bellingham",
        "from_club": "Borussia Dortmund", "from_league": "Bundesliga",
        "to_club": "Real Madrid", "to_league": "La Liga",
        "fee_eur_m": 103, "fee_type": "permanent",
        "deal_context": "club_decision",
        "position": "CM", "transfer_date": "2023-06-14",
        "transfer_window": "2023_summer",
        "notes": "€103m. Youngest English player at Madrid. Immediate Ballon d'Or contender.",
    },
    {
        "player_name": "Joško Gvardiol",
        "from_club": "RB Leipzig", "from_league": "Bundesliga",
        "to_club": "Manchester City", "to_league": "Premier League",
        "fee_eur_m": 90, "fee_type": "permanent",
        "deal_context": "club_decision",
        "position": "CD", "transfer_date": "2023-08-05",
        "transfer_window": "2023_summer",
        "notes": "Most expensive defender ever at the time. Versatile CB/LB.",
    },
    {
        "player_name": "Neymar",
        "from_club": "Paris Saint-Germain", "from_league": "Ligue 1",
        "to_club": "Al Hilal", "to_league": "Saudi Pro League",
        "fee_eur_m": 90, "fee_type": "permanent",
        "deal_context": "club_decision",
        "position": "WF", "transfer_date": "2023-08-15",
        "transfer_window": "2023_summer",
        "notes": "End of PSG era. €90m to Saudi. Played only 7 matches due to ACL injury.",
    },
    {
        "player_name": "Rasmus Højlund",
        "from_club": "Atalanta", "from_league": "Serie A",
        "to_club": "Manchester United", "to_league": "Premier League",
        "fee_eur_m": 72, "fee_type": "permanent",
        "deal_context": "club_decision",
        "position": "CF", "transfer_date": "2023-08-05",
        "transfer_window": "2023_summer",
        "notes": "€72m. 20-year-old Danish striker. United's long-term #9 plan.",
    },
    {
        "player_name": "Dominik Szoboszlai",
        "from_club": "RB Leipzig", "from_league": "Bundesliga",
        "to_club": "Liverpool", "to_league": "Premier League",
        "fee_eur_m": 70, "fee_type": "permanent",
        "deal_context": "release_clause",
        "position": "CM", "transfer_date": "2023-06-29",
        "transfer_window": "2023_summer",
        "notes": "€70m release clause. Hungarian captain. Klopp's midfield overhaul.",
    },
    {
        "player_name": "Mason Mount",
        "from_club": "Chelsea", "from_league": "Premier League",
        "to_club": "Manchester United", "to_league": "Premier League",
        "fee_eur_m": 65, "fee_type": "permanent",
        "deal_context": "contract_expiring",
        "position": "AM", "transfer_date": "2023-07-05",
        "transfer_window": "2023_summer",
        "notes": "One year left on contract. Chelsea academy product. Injury-plagued at United.",
    },
    {
        "player_name": "Kai Havertz",
        "from_club": "Chelsea", "from_league": "Premier League",
        "to_club": "Arsenal", "to_league": "Premier League",
        "fee_eur_m": 65, "fee_type": "permanent",
        "deal_context": "club_decision",
        "position": "CF", "transfer_date": "2023-06-28",
        "transfer_window": "2023_summer",
        "notes": "Arsenal reinvented him as a false 9/pressing forward. CL winner at Chelsea.",
    },
    {
        "player_name": "Sandro Tonali",
        "from_club": "AC Milan", "from_league": "Serie A",
        "to_club": "Newcastle United", "to_league": "Premier League",
        "fee_eur_m": 64, "fee_type": "permanent",
        "deal_context": "club_decision",
        "position": "CM", "transfer_date": "2023-07-05",
        "transfer_window": "2023_summer",
        "notes": "Italian international. Banned 10 months for betting violations shortly after.",
    },
    {
        "player_name": "Romeo Lavia",
        "from_club": "Southampton", "from_league": "Premier League",
        "to_club": "Chelsea", "to_league": "Premier League",
        "fee_eur_m": 62, "fee_type": "permanent",
        "deal_context": "club_decision",
        "position": "DM", "transfer_date": "2023-08-29",
        "transfer_window": "2023_summer",
        "notes": "Chelsea beat Liverpool. £58m for 19-year-old from relegated Southampton.",
    },
    {
        "player_name": "Christopher Nkunku",
        "from_club": "RB Leipzig", "from_league": "Bundesliga",
        "to_club": "Chelsea", "to_league": "Premier League",
        "fee_eur_m": 60, "fee_type": "permanent",
        "deal_context": "release_clause",
        "position": "CF", "transfer_date": "2023-07-01",
        "transfer_window": "2023_summer",
        "notes": "€60m release clause. Pre-agreed in winter. Injured in preseason.",
    },
    {
        "player_name": "Moussa Diaby",
        "from_club": "Bayer Leverkusen", "from_league": "Bundesliga",
        "to_club": "Aston Villa", "to_league": "Premier League",
        "fee_eur_m": 55, "fee_type": "permanent",
        "deal_context": "club_decision",
        "position": "WF", "transfer_date": "2023-07-18",
        "transfer_window": "2023_summer",
        "notes": "Villa's record signing at the time. Rapid French winger.",
    },
    {
        "player_name": "André Onana",
        "from_club": "Inter Milan", "from_league": "Serie A",
        "to_club": "Manchester United", "to_league": "Premier League",
        "fee_eur_m": 50, "fee_type": "permanent",
        "deal_context": "club_decision",
        "position": "GK", "transfer_date": "2023-07-20",
        "transfer_window": "2023_summer",
        "notes": "CL finalist GK. Ten Hag reunion from Ajax. Ball-playing keeper.",
    },
    {
        "player_name": "James Maddison",
        "from_club": "Leicester City", "from_league": "Premier League",
        "to_club": "Tottenham Hotspur", "to_league": "Premier League",
        "fee_eur_m": 40, "fee_type": "permanent",
        "deal_context": "club_decision",
        "position": "AM", "transfer_date": "2023-06-22",
        "transfer_window": "2023_summer",
        "notes": "Spurs signed early from relegated Leicester. England international.",
    },
    {
        "player_name": "Alexis Mac Allister",
        "from_club": "Brighton", "from_league": "Premier League",
        "to_club": "Liverpool", "to_league": "Premier League",
        "fee_eur_m": 35, "fee_type": "permanent",
        "deal_context": "release_clause",
        "position": "CM", "transfer_date": "2023-06-14",
        "transfer_window": "2023_summer",
        "notes": "World Cup winner. Release clause. Key part of Klopp's midfield rebuild.",
    },
    {
        "player_name": "Mateo Kovačić",
        "from_club": "Chelsea", "from_league": "Premier League",
        "to_club": "Manchester City", "to_league": "Premier League",
        "fee_eur_m": 30, "fee_type": "permanent",
        "deal_context": "contract_expiring",
        "position": "CM", "transfer_date": "2023-07-06",
        "transfer_window": "2023_summer",
        "notes": "Final year of Chelsea contract. City got a bargain for Treble squad depth.",
    },
    {
        "player_name": "Robert Sánchez",
        "from_club": "Brighton", "from_league": "Premier League",
        "to_club": "Chelsea", "to_league": "Premier League",
        "fee_eur_m": 25, "fee_type": "permanent",
        "deal_context": "club_decision",
        "position": "GK", "transfer_date": "2023-08-23",
        "transfer_window": "2023_summer",
        "notes": "Chelsea's new #1. Part of Brighton raid that summer.",
    },
    {
        "player_name": "Ederson",
        "from_club": "Atalanta", "from_league": "Serie A",
        "to_club": "Aston Villa", "to_league": "Premier League",
        "fee_eur_m": 50, "fee_type": "permanent",
        "deal_context": "release_clause",
        "position": "CM", "transfer_date": "2023-08-31",
        "transfer_window": "2023_summer",
        "notes": "Brazilian midfielder from Atalanta. Villa's CL squad addition.",
    },
    {
        "player_name": "Micky van de Ven",
        "from_club": "VfL Wolfsburg", "from_league": "Bundesliga",
        "to_club": "Tottenham Hotspur", "to_league": "Premier League",
        "fee_eur_m": 43, "fee_type": "permanent",
        "deal_context": "club_decision",
        "position": "CD", "transfer_date": "2023-08-04",
        "transfer_window": "2023_summer",
        "notes": "Dutch CB with extreme pace. Became one of PL's best defenders.",
    },
    {
        "player_name": "Gonçalo Ramos",
        "from_club": "Benfica", "from_league": "Primeira Liga",
        "to_club": "Paris Saint-Germain", "to_league": "Ligue 1",
        "fee_eur_m": 65, "fee_type": "permanent",
        "deal_context": "club_decision",
        "position": "CF", "transfer_date": "2023-08-19",
        "transfer_window": "2023_summer",
        "notes": "WC 2022 hat-trick hero. PSG's Mbappé successor attempt.",
    },
    {
        "player_name": "Randal Kolo Muani",
        "from_club": "Eintracht Frankfurt", "from_league": "Bundesliga",
        "to_club": "Paris Saint-Germain", "to_league": "Ligue 1",
        "fee_eur_m": 90, "fee_type": "permanent",
        "deal_context": "release_clause",
        "position": "CF", "transfer_date": "2023-09-01",
        "transfer_window": "2023_summer",
        "notes": "€90m deadline day. PSG's most expensive signing. Flopped spectacularly.",
    },
    {
        "player_name": "Ousmane Dembélé",
        "from_club": "Barcelona", "from_league": "La Liga",
        "to_club": "Paris Saint-Germain", "to_league": "Ligue 1",
        "fee_eur_m": 50, "fee_type": "permanent",
        "deal_context": "club_decision",
        "position": "WF", "transfer_date": "2023-08-13",
        "transfer_window": "2023_summer",
        "notes": "€50m. Left Barca after finally settling. PSG's post-Messi rebuild.",
    },
    {
        "player_name": "Ilkay Gündogan",
        "from_club": "Manchester City", "from_league": "Premier League",
        "to_club": "Barcelona", "to_league": "La Liga",
        "fee_eur_m": 0, "fee_type": "free",
        "deal_context": "contract_expiring",
        "position": "CM", "transfer_date": "2023-07-04",
        "transfer_window": "2023_summer",
        "notes": "Left as Treble-winning captain. Free transfer to Barcelona.",
    },
    {
        "player_name": "Marcus Thuram",
        "from_club": "Borussia Mönchengladbach", "from_league": "Bundesliga",
        "to_club": "Inter Milan", "to_league": "Serie A",
        "fee_eur_m": 0, "fee_type": "free",
        "deal_context": "contract_expiring",
        "position": "CF", "transfer_date": "2023-07-01",
        "transfer_window": "2023_summer",
        "notes": "Free transfer bargain. Became one of Serie A's best strikers at Inter.",
    },
    {
        "player_name": "Jérémy Doku",
        "from_club": "Rennes", "from_league": "Ligue 1",
        "to_club": "Manchester City", "to_league": "Premier League",
        "fee_eur_m": 60, "fee_type": "permanent",
        "deal_context": "club_decision",
        "position": "WF", "transfer_date": "2023-08-30",
        "transfer_window": "2023_summer",
        "notes": "Belgian dribbler. Deadline day signing. €60m for 21-year-old.",
    },
    {
        "player_name": "Harry Kane",
        "from_club": "Tottenham Hotspur", "from_league": "Premier League",
        "to_club": "Bayern Munich", "to_league": "Bundesliga",
        "fee_eur_m": 95, "fee_type": "permanent",
        "deal_context": "transfer_request",
        "position": "CF", "transfer_date": "2023-08-12",
        "transfer_window": "2023_summer",
        "notes": "Finally left Spurs. £100m. All-time PL top scorer. 44 goals in first Bayern season.",
    },
    {
        "player_name": "Pervis Estupiñán",
        "from_club": "Villarreal", "from_league": "La Liga",
        "to_club": "Brighton", "to_league": "Premier League",
        "fee_eur_m": 18, "fee_type": "permanent",
        "deal_context": "club_decision",
        "position": "WD", "transfer_date": "2022-08-11",
        "transfer_window": "2022_summer",
        "notes": "Ecuadorian LB. One of Brighton's smartest buys under De Zerbi era.",
    },
    {
        "player_name": "Kaoru Mitoma",
        "from_club": "Royale Union Saint-Gilloise", "from_league": "Belgian Pro League",
        "to_club": "Brighton", "to_league": "Premier League",
        "fee_eur_m": 3, "fee_type": "permanent",
        "deal_context": "club_decision",
        "position": "WF", "transfer_date": "2022-07-01",
        "transfer_window": "2022_summer",
        "notes": "Japanese winger. €3m bargain. Became one of PL's most exciting dribblers.",
    },
    {
        "player_name": "Pedro Porro",
        "from_club": "Sporting CP", "from_league": "Primeira Liga",
        "to_club": "Tottenham Hotspur", "to_league": "Premier League",
        "fee_eur_m": 45, "fee_type": "permanent",
        "deal_context": "club_decision",
        "position": "WD", "transfer_date": "2023-01-31",
        "transfer_window": "2023_jan",
        "notes": "Loan with obligation. Spanish international. Attacking right-back.",
    },
    {
        "player_name": "Joao Cancelo",
        "from_club": "Manchester City", "from_league": "Premier League",
        "to_club": "Bayern Munich", "to_league": "Bundesliga",
        "fee_eur_m": 0, "fee_type": "loan",
        "deal_context": "player_surplus",
        "position": "WD", "transfer_date": "2023-01-31",
        "transfer_window": "2023_jan",
        "notes": "Fell out with Guardiola. Bayern loan. Subsequently went to Barcelona.",
    },
    {
        "player_name": "Jurriën Timber",
        "from_club": "Ajax", "from_league": "Eredivisie",
        "to_club": "Arsenal", "to_league": "Premier League",
        "fee_eur_m": 40, "fee_type": "permanent",
        "deal_context": "club_decision",
        "position": "CD", "transfer_date": "2023-07-14",
        "transfer_window": "2023_summer",
        "notes": "Dutch international. ACL in first game. Came back strong in 2024-25.",
    },
    {
        "player_name": "Kim Min-jae",
        "from_club": "Napoli", "from_league": "Serie A",
        "to_club": "Bayern Munich", "to_league": "Bundesliga",
        "fee_eur_m": 50, "fee_type": "permanent",
        "deal_context": "release_clause",
        "position": "CD", "transfer_date": "2023-07-12",
        "transfer_window": "2023_summer",
        "notes": "€50m release clause. South Korean CB. Scudetto winner at Napoli.",
    },
    {
        "player_name": "Vitor Roque",
        "from_club": "Athletico Paranaense", "from_league": "Brasileirão",
        "to_club": "Barcelona", "to_league": "La Liga",
        "fee_eur_m": 40, "fee_type": "permanent",
        "deal_context": "club_decision",
        "position": "CF", "transfer_date": "2024-01-01",
        "transfer_window": "2024_jan",
        "notes": "Brazilian wonderkid. €40m. Barely played, loaned to Betis months later.",
    },
    {
        "player_name": "Youri Tielemans",
        "from_club": "Leicester City", "from_league": "Premier League",
        "to_club": "Aston Villa", "to_league": "Premier League",
        "fee_eur_m": 0, "fee_type": "free",
        "deal_context": "contract_expiring",
        "position": "CM", "transfer_date": "2023-07-03",
        "transfer_window": "2023_summer",
        "notes": "Free from relegated Leicester. Belgian international. Emery wanted experience.",
    },
    {
        "player_name": "Douglas Luiz",
        "from_club": "Aston Villa", "from_league": "Premier League",
        "to_club": "Juventus", "to_league": "Serie A",
        "fee_eur_m": 50, "fee_type": "permanent",
        "deal_context": "club_decision",
        "position": "CM", "transfer_date": "2024-06-27",
        "transfer_window": "2024_summer",
        "notes": "PSR-driven sale. Part of deal included McKennie + Iling-Junior to Villa.",
    },
    {
        "player_name": "Teun Koopmeiners",
        "from_club": "Atalanta", "from_league": "Serie A",
        "to_club": "Juventus", "to_league": "Serie A",
        "fee_eur_m": 54, "fee_type": "permanent",
        "deal_context": "transfer_request",
        "position": "CM", "transfer_date": "2024-08-28",
        "transfer_window": "2024_summer",
        "notes": "Dutch international. Refused to train to force move. €54m plus add-ons.",
    },
    {
        "player_name": "Nico González",
        "from_club": "Fiorentina", "from_league": "Serie A",
        "to_club": "Juventus", "to_league": "Serie A",
        "fee_eur_m": 33, "fee_type": "permanent",
        "deal_context": "club_decision",
        "position": "WF", "transfer_date": "2024-08-09",
        "transfer_window": "2024_summer",
        "notes": "Argentine winger. Juve's summer rebuild under Thiago Motta.",
    },

    # ── Summer 2024 window ───────────────────────────────────────────────────
    {
        "player_name": "Julián Álvarez",
        "from_club": "Manchester City", "from_league": "Premier League",
        "to_club": "Atlético Madrid", "to_league": "La Liga",
        "fee_eur_m": 75, "fee_type": "permanent",
        "deal_context": "transfer_request",
        "position": "CF", "transfer_date": "2024-08-12",
        "transfer_window": "2024_summer",
        "notes": "Wanted guaranteed starting role. €75m plus add-ons to €95m.",
    },
    {
        "player_name": "Leny Yoro",
        "from_club": "Lille", "from_league": "Ligue 1",
        "to_club": "Manchester United", "to_league": "Premier League",
        "fee_eur_m": 62, "fee_type": "permanent",
        "deal_context": "club_decision",
        "position": "CD", "transfer_date": "2024-07-18",
        "transfer_window": "2024_summer",
        "notes": "18-year-old CB. United beat Real Madrid. €62m for a teenager.",
    },
    {
        "player_name": "Dominic Solanke",
        "from_club": "AFC Bournemouth", "from_league": "Premier League",
        "to_club": "Tottenham Hotspur", "to_league": "Premier League",
        "fee_eur_m": 65, "fee_type": "permanent",
        "deal_context": "release_clause",
        "position": "CF", "transfer_date": "2024-08-10",
        "transfer_window": "2024_summer",
        "notes": "£65m release clause. 19 PL goals the prior season.",
    },
    {
        "player_name": "Pedro Neto",
        "from_club": "Wolverhampton Wanderers", "from_league": "Premier League",
        "to_club": "Chelsea", "to_league": "Premier League",
        "fee_eur_m": 60, "fee_type": "permanent",
        "deal_context": "club_decision",
        "position": "WF", "transfer_date": "2024-08-11",
        "transfer_window": "2024_summer",
        "notes": "Chelsea continued to raid PL rivals. Portuguese winger with pace.",
    },
    {
        "player_name": "Moussa Diaby",
        "from_club": "Aston Villa", "from_league": "Premier League",
        "to_club": "Al Ittihad", "to_league": "Saudi Pro League",
        "fee_eur_m": 60, "fee_type": "permanent",
        "deal_context": "club_decision",
        "position": "WF", "transfer_date": "2024-07-29",
        "transfer_window": "2024_summer",
        "notes": "Villa sold after one season for same price. Saudi money.",
    },
    {
        "player_name": "Dani Olmo",
        "from_club": "RB Leipzig", "from_league": "Bundesliga",
        "to_club": "Barcelona", "to_league": "La Liga",
        "fee_eur_m": 55, "fee_type": "permanent",
        "deal_context": "club_decision",
        "position": "AM", "transfer_date": "2024-08-09",
        "transfer_window": "2024_summer",
        "notes": "Euro 2024 star. Barca's registration saga followed.",
    },
    {
        "player_name": "Michael Olise",
        "from_club": "Crystal Palace", "from_league": "Premier League",
        "to_club": "Bayern Munich", "to_league": "Bundesliga",
        "fee_eur_m": 53, "fee_type": "permanent",
        "deal_context": "release_clause",
        "position": "WF", "transfer_date": "2024-07-07",
        "transfer_window": "2024_summer",
        "notes": "Olympic gold medallist. Bayern triggered release clause.",
    },
    {
        "player_name": "Joao Felix",
        "from_club": "Atlético Madrid", "from_league": "La Liga",
        "to_club": "Chelsea", "to_league": "Premier League",
        "fee_eur_m": 52, "fee_type": "permanent",
        "deal_context": "club_decision",
        "position": "AM", "transfer_date": "2024-08-22",
        "transfer_window": "2024_summer",
        "notes": "Obligation from loan converted. Atlético moved on from the saga.",
    },
    {
        "player_name": "João Palhinha",
        "from_club": "Fulham", "from_league": "Premier League",
        "to_club": "Bayern Munich", "to_league": "Bundesliga",
        "fee_eur_m": 51, "fee_type": "permanent",
        "deal_context": "club_decision",
        "position": "DM", "transfer_date": "2024-08-01",
        "transfer_window": "2024_summer",
        "notes": "Deal collapsed in 2023, completed a year later. Bayern's anchor.",
    },
    {
        "player_name": "Amadou Onana",
        "from_club": "Everton", "from_league": "Premier League",
        "to_club": "Aston Villa", "to_league": "Premier League",
        "fee_eur_m": 50, "fee_type": "permanent",
        "deal_context": "club_decision",
        "position": "DM", "transfer_date": "2024-08-07",
        "transfer_window": "2024_summer",
        "notes": "Belgian international. Villa strengthened midfield for Champions League.",
    },
    {
        "player_name": "Désiré Doué",
        "from_club": "Rennes", "from_league": "Ligue 1",
        "to_club": "Paris Saint-Germain", "to_league": "Ligue 1",
        "fee_eur_m": 50, "fee_type": "permanent",
        "deal_context": "club_decision",
        "position": "AM", "transfer_date": "2024-08-16",
        "transfer_window": "2024_summer",
        "notes": "French teenager. PSG beat Bayern Munich in race to sign.",
    },
    {
        "player_name": "Riccardo Calafiori",
        "from_club": "Bologna", "from_league": "Serie A",
        "to_club": "Arsenal", "to_league": "Premier League",
        "fee_eur_m": 45, "fee_type": "permanent",
        "deal_context": "club_decision",
        "position": "CD", "transfer_date": "2024-07-22",
        "transfer_window": "2024_summer",
        "notes": "Euro 2024 standout. Versatile CB/LB for Arteta's system.",
    },
    {
        "player_name": "Matthijs de Ligt",
        "from_club": "Bayern Munich", "from_league": "Bundesliga",
        "to_club": "Manchester United", "to_league": "Premier League",
        "fee_eur_m": 45, "fee_type": "permanent",
        "deal_context": "club_decision",
        "position": "CD", "transfer_date": "2024-08-13",
        "transfer_window": "2024_summer",
        "notes": "Third major club move. Ten Hag reunion again.",
    },
    {
        "player_name": "Ian Maatsen",
        "from_club": "Chelsea", "from_league": "Premier League",
        "to_club": "Aston Villa", "to_league": "Premier League",
        "fee_eur_m": 44, "fee_type": "permanent",
        "deal_context": "release_clause",
        "position": "WD", "transfer_date": "2024-07-01",
        "transfer_window": "2024_summer",
        "notes": "CL semi-finalist at Dortmund on loan. Villa triggered release clause.",
    },
    {
        "player_name": "Joshua Zirkzee",
        "from_club": "Bologna", "from_league": "Serie A",
        "to_club": "Manchester United", "to_league": "Premier League",
        "fee_eur_m": 42, "fee_type": "permanent",
        "deal_context": "release_clause",
        "position": "CF", "transfer_date": "2024-07-14",
        "transfer_window": "2024_summer",
        "notes": "Dutch striker. €42.5m release clause triggered. Bologna's star departure.",
    },
    {
        "player_name": "Georginio Rutter",
        "from_club": "Leeds United", "from_league": "Championship",
        "to_club": "Brighton", "to_league": "Premier League",
        "fee_eur_m": 40, "fee_type": "permanent",
        "deal_context": "release_clause",
        "position": "AM", "transfer_date": "2024-08-06",
        "transfer_window": "2024_summer",
        "notes": "Brighton triggered release clause from relegated Leeds.",
    },
    {
        "player_name": "Emile Smith Rowe",
        "from_club": "Arsenal", "from_league": "Premier League",
        "to_club": "Fulham", "to_league": "Premier League",
        "fee_eur_m": 35, "fee_type": "permanent",
        "deal_context": "player_surplus",
        "position": "AM", "transfer_date": "2024-08-02",
        "transfer_window": "2024_summer",
        "notes": "Arsenal academy graduate. Needed regular minutes elsewhere.",
    },
    {
        "player_name": "Endrick",
        "from_club": "Palmeiras", "from_league": "Brasileirão",
        "to_club": "Real Madrid", "to_league": "La Liga",
        "fee_eur_m": 35, "fee_type": "permanent",
        "deal_context": "pre_contract",
        "position": "CF", "transfer_date": "2024-07-21",
        "transfer_window": "2024_summer",
        "notes": "Pre-agreed 2022 for €35m plus €25m add-ons. Joined on 18th birthday.",
    },
    {
        "player_name": "Kylian Mbappé",
        "from_club": "Paris Saint-Germain", "from_league": "Ligue 1",
        "to_club": "Real Madrid", "to_league": "La Liga",
        "fee_eur_m": 0, "fee_type": "free",
        "deal_context": "contract_expiring",
        "position": "CF", "transfer_date": "2024-07-01",
        "transfer_window": "2024_summer",
        "notes": "Free transfer after running down PSG contract. Biggest free transfer in history.",
    },
    {
        "player_name": "Niclas Füllkrug",
        "from_club": "Borussia Dortmund", "from_league": "Bundesliga",
        "to_club": "West Ham United", "to_league": "Premier League",
        "fee_eur_m": 27, "fee_type": "permanent",
        "deal_context": "club_decision",
        "position": "CF", "transfer_date": "2024-08-10",
        "transfer_window": "2024_summer",
        "notes": "German international. CL finalist at Dortmund.",
    },
    {
        "player_name": "Savinho",
        "from_club": "Troyes", "from_league": "Ligue 1",
        "to_club": "Manchester City", "to_league": "Premier League",
        "fee_eur_m": 25, "fee_type": "permanent",
        "deal_context": "club_decision",
        "position": "WF", "transfer_date": "2024-07-18",
        "transfer_window": "2024_summer",
        "notes": "Via Girona loan (City Football Group). Brazilian winger.",
    },
    {
        "player_name": "Mats Hummels",
        "from_club": "Borussia Dortmund", "from_league": "Bundesliga",
        "to_club": "Roma", "to_league": "Serie A",
        "fee_eur_m": 0, "fee_type": "free",
        "deal_context": "contract_expiring",
        "position": "CD", "transfer_date": "2024-09-04",
        "transfer_window": "2024_summer",
        "notes": "CL finalist at 35. Roma signed him free but barely played him.",
    },
    {
        "player_name": "Manuel Ugarte",
        "from_club": "Paris Saint-Germain", "from_league": "Ligue 1",
        "to_club": "Manchester United", "to_league": "Premier League",
        "fee_eur_m": 50, "fee_type": "permanent",
        "deal_context": "club_decision",
        "position": "DM", "transfer_date": "2024-08-30",
        "transfer_window": "2024_summer",
        "notes": "Uruguayan DM. PSG let go after one season. Loan with obligation.",
    },
    {
        "player_name": "Archie Gray",
        "from_club": "Leeds United", "from_league": "Championship",
        "to_club": "Tottenham Hotspur", "to_league": "Premier League",
        "fee_eur_m": 34, "fee_type": "permanent",
        "deal_context": "club_decision",
        "position": "CM", "transfer_date": "2024-07-03",
        "transfer_window": "2024_summer",
        "notes": "18-year-old Leeds academy product. Versatile midfielder/RB.",
    },
    {
        "player_name": "Kiernan Dewsbury-Hall",
        "from_club": "Leicester City", "from_league": "Championship",
        "to_club": "Chelsea", "to_league": "Premier League",
        "fee_eur_m": 35, "fee_type": "permanent",
        "deal_context": "club_decision",
        "position": "CM", "transfer_date": "2024-07-02",
        "transfer_window": "2024_summer",
        "notes": "Maresca reunion from Leicester's title-winning Championship season.",
    },
    {
        "player_name": "Raphaël Varane",
        "from_club": "Manchester United", "from_league": "Premier League",
        "to_club": "Como", "to_league": "Serie A",
        "fee_eur_m": 0, "fee_type": "free",
        "deal_context": "contract_expiring",
        "position": "CD", "transfer_date": "2024-07-01",
        "transfer_window": "2024_summer",
        "notes": "Left United on a free. Brief retirement consideration before Como.",
    },
    {
        "player_name": "João Neves",
        "from_club": "Benfica", "from_league": "Primeira Liga",
        "to_club": "Paris Saint-Germain", "to_league": "Ligue 1",
        "fee_eur_m": 60, "fee_type": "permanent",
        "deal_context": "club_decision",
        "position": "CM", "transfer_date": "2024-08-02",
        "transfer_window": "2024_summer",
        "notes": "Portuguese wonderkid. €60m plus €10m add-ons. Benfica's latest export.",
    },
    {
        "player_name": "Mikel Merino",
        "from_club": "Real Sociedad", "from_league": "La Liga",
        "to_club": "Arsenal", "to_league": "Premier League",
        "fee_eur_m": 32, "fee_type": "permanent",
        "deal_context": "club_decision",
        "position": "CM", "transfer_date": "2024-08-27",
        "transfer_window": "2024_summer",
        "notes": "Euro 2024 winner. Physical midfielder for Arteta's squad depth.",
    },
    {
        "player_name": "Aaron Ramsdale",
        "from_club": "Arsenal", "from_league": "Premier League",
        "to_club": "Southampton", "to_league": "Premier League",
        "fee_eur_m": 20, "fee_type": "permanent",
        "deal_context": "player_surplus",
        "position": "GK", "transfer_date": "2024-08-30",
        "transfer_window": "2024_summer",
        "notes": "Lost #1 spot to Raya. Needed to be starting somewhere.",
    },
    {
        "player_name": "Chadi Riad",
        "from_club": "Barcelona", "from_league": "La Liga",
        "to_club": "Crystal Palace", "to_league": "Premier League",
        "fee_eur_m": 15, "fee_type": "permanent",
        "deal_context": "club_decision",
        "position": "CD", "transfer_date": "2024-08-08",
        "transfer_window": "2024_summer",
        "notes": "Moroccan CB. Palace signed from Barça via Betis loan.",
    },
    {
        "player_name": "Willian Pacho",
        "from_club": "Eintracht Frankfurt", "from_league": "Bundesliga",
        "to_club": "Paris Saint-Germain", "to_league": "Ligue 1",
        "fee_eur_m": 40, "fee_type": "permanent",
        "deal_context": "club_decision",
        "position": "CD", "transfer_date": "2024-08-10",
        "transfer_window": "2024_summer",
        "notes": "Ecuadorian CB. PSG's defensive reinforcement. €40m.",
    },
    {
        "player_name": "Iliman Ndiaye",
        "from_club": "Marseille", "from_league": "Ligue 1",
        "to_club": "Everton", "to_league": "Premier League",
        "fee_eur_m": 19, "fee_type": "permanent",
        "deal_context": "club_decision",
        "position": "AM", "transfer_date": "2024-08-13",
        "transfer_window": "2024_summer",
        "notes": "Senegalese forward. Back to England from one-year Marseille stint.",
    },
    {
        "player_name": "Daichi Kamada",
        "from_club": "Lazio", "from_league": "Serie A",
        "to_club": "Crystal Palace", "to_league": "Premier League",
        "fee_eur_m": 0, "fee_type": "free",
        "deal_context": "contract_expiring",
        "position": "AM", "transfer_date": "2024-07-01",
        "transfer_window": "2024_summer",
        "notes": "Japanese international. Free from Lazio after one season.",
    },
    {
        "player_name": "Yankuba Minteh",
        "from_club": "Newcastle United", "from_league": "Premier League",
        "to_club": "Brighton", "to_league": "Premier League",
        "fee_eur_m": 33, "fee_type": "permanent",
        "deal_context": "club_decision",
        "position": "WF", "transfer_date": "2024-07-08",
        "transfer_window": "2024_summer",
        "notes": "Gambian winger. Impressed on Feyenoord loan. PSR forced Newcastle sale.",
    },
    {
        "player_name": "Federico Chiesa",
        "from_club": "Juventus", "from_league": "Serie A",
        "to_club": "Liverpool", "to_league": "Premier League",
        "fee_eur_m": 12, "fee_type": "permanent",
        "deal_context": "player_surplus",
        "position": "WF", "transfer_date": "2024-08-29",
        "transfer_window": "2024_summer",
        "notes": "Deadline day bargain. One year left on contract. Injury concerns.",
    },
    {
        "player_name": "Conor Gallagher",
        "from_club": "Chelsea", "from_league": "Premier League",
        "to_club": "Atlético Madrid", "to_league": "La Liga",
        "fee_eur_m": 42, "fee_type": "permanent",
        "deal_context": "club_decision",
        "position": "CM", "transfer_date": "2024-08-21",
        "transfer_window": "2024_summer",
        "notes": "Swap-ish deal with Felix. Chelsea academy graduate. PSR move.",
    },
    {
        "player_name": "Samu Omorodion",
        "from_club": "Atlético Madrid", "from_league": "La Liga",
        "to_club": "Porto", "to_league": "Primeira Liga",
        "fee_eur_m": 15, "fee_type": "permanent",
        "deal_context": "club_decision",
        "position": "CF", "transfer_date": "2024-08-16",
        "transfer_window": "2024_summer",
        "notes": "Chelsea deal collapsed over personal terms. Porto stepped in at €15m.",
    },
    {
        "player_name": "Elliot Anderson",
        "from_club": "Newcastle United", "from_league": "Premier League",
        "to_club": "Nottingham Forest", "to_league": "Premier League",
        "fee_eur_m": 41, "fee_type": "permanent",
        "deal_context": "club_decision",
        "position": "CM", "transfer_date": "2024-07-01",
        "transfer_window": "2024_summer",
        "notes": "PSR-driven sale. Newcastle needed to sell before June 30 deadline.",
    },
    {
        "player_name": "Youssouf Fofana",
        "from_club": "AS Monaco", "from_league": "Ligue 1",
        "to_club": "AC Milan", "to_league": "Serie A",
        "fee_eur_m": 25, "fee_type": "permanent",
        "deal_context": "contract_expiring",
        "position": "CM", "transfer_date": "2024-08-14",
        "transfer_window": "2024_summer",
        "notes": "French international. Final year of contract. Milan got a discount.",
    },
    {
        "player_name": "Eddie Nketiah",
        "from_club": "Arsenal", "from_league": "Premier League",
        "to_club": "Crystal Palace", "to_league": "Premier League",
        "fee_eur_m": 30, "fee_type": "permanent",
        "deal_context": "player_surplus",
        "position": "CF", "transfer_date": "2024-08-27",
        "transfer_window": "2024_summer",
        "notes": "Arsenal academy product. Palace signed after Marseille deal collapsed.",
    },

    # ── January 2025 window ──────────────────────────────────────────────────
    {
        "player_name": "Jhon Durán",
        "from_club": "Aston Villa", "from_league": "Premier League",
        "to_club": "Al Nassr", "to_league": "Saudi Pro League",
        "fee_eur_m": 77, "fee_type": "permanent",
        "deal_context": "club_decision",
        "position": "CF", "transfer_date": "2025-01-28",
        "transfer_window": "2025_jan",
        "notes": "Club-record sale for Villa. Durán chose Saudi move over staying in PL.",
    },
    {
        "player_name": "Khvicha Kvaratskhelia",
        "from_club": "Napoli", "from_league": "Serie A",
        "to_club": "Paris Saint-Germain", "to_league": "Ligue 1",
        "fee_eur_m": 70, "fee_type": "permanent",
        "deal_context": "transfer_request",
        "position": "WF", "transfer_date": "2025-01-17",
        "transfer_window": "2025_jan",
        "notes": "Handed in transfer request. Conte accepted departure.",
    },
    {
        "player_name": "Omar Marmoush",
        "from_club": "Eintracht Frankfurt", "from_league": "Bundesliga",
        "to_club": "Manchester City", "to_league": "Premier League",
        "fee_eur_m": 75, "fee_type": "permanent",
        "deal_context": "release_clause",
        "position": "CF", "transfer_date": "2025-01-23",
        "transfer_window": "2025_jan",
        "notes": "Release clause triggered after 15-goal Bundesliga half-season.",
    },
    {
        "player_name": "Patrick Dorgu",
        "from_club": "Lecce", "from_league": "Serie A",
        "to_club": "Manchester United", "to_league": "Premier League",
        "fee_eur_m": 30, "fee_type": "permanent",
        "deal_context": "club_decision",
        "position": "WD", "transfer_date": "2025-01-30",
        "transfer_window": "2025_jan",
        "notes": "Versatile Danish wing-back. Can play both flanks.",
    },
    {
        "player_name": "Abdukodir Khusanov",
        "from_club": "Lens", "from_league": "Ligue 1",
        "to_club": "Manchester City", "to_league": "Premier League",
        "fee_eur_m": 40, "fee_type": "permanent",
        "deal_context": "club_decision",
        "position": "CD", "transfer_date": "2025-01-19",
        "transfer_window": "2025_jan",
        "notes": "20-year-old Uzbek CB. Part of City's defensive rebuild.",
    },
    {
        "player_name": "Vitor Reis",
        "from_club": "Palmeiras", "from_league": "Brasileirão",
        "to_club": "Manchester City", "to_league": "Premier League",
        "fee_eur_m": 37, "fee_type": "permanent",
        "deal_context": "club_decision",
        "position": "CD", "transfer_date": "2025-01-24",
        "transfer_window": "2025_jan",
        "notes": "Brazilian teen CB. Long-term investment from Palmeiras.",
    },
    {
        "player_name": "Giorgi Mamardashvili",
        "from_club": "Valencia", "from_league": "La Liga",
        "to_club": "Liverpool", "to_league": "Premier League",
        "fee_eur_m": 35, "fee_type": "pre_agreed",
        "deal_context": "pre_contract",
        "position": "GK", "transfer_date": "2025-01-01",
        "transfer_window": "2025_jan",
        "notes": "Deal agreed summer 2024, completed Jan 2025. Alisson successor plan.",
    },
    {
        "player_name": "Alejandro Garnacho",
        "from_club": "Manchester United", "from_league": "Premier League",
        "to_club": "Napoli", "to_league": "Serie A",
        "fee_eur_m": 38, "fee_type": "permanent",
        "deal_context": "player_surplus",
        "position": "WF", "transfer_date": "2025-01-27",
        "transfer_window": "2025_jan",
        "notes": "Fell out of favour under Amorim. Napoli saw Kvaratskhelia replacement.",
    },
    {
        "player_name": "Randal Kolo Muani",
        "from_club": "Paris Saint-Germain", "from_league": "Ligue 1",
        "to_club": "Juventus", "to_league": "Serie A",
        "fee_eur_m": 0, "fee_type": "loan",
        "deal_context": "player_surplus",
        "position": "CF", "transfer_date": "2025-01-16",
        "transfer_window": "2025_jan",
        "notes": "Loan until end of season. Surplus to requirements at PSG.",
    },
    {
        "player_name": "Marcus Rashford",
        "from_club": "Manchester United", "from_league": "Premier League",
        "to_club": "Aston Villa", "to_league": "Premier League",
        "fee_eur_m": 0, "fee_type": "loan",
        "deal_context": "player_surplus",
        "position": "WF", "transfer_date": "2025-01-31",
        "transfer_window": "2025_jan",
        "notes": "Loan after publicly stating desire to leave. Barca fell through.",
    },
    {
        "player_name": "Mathys Tel",
        "from_club": "Bayern Munich", "from_league": "Bundesliga",
        "to_club": "Tottenham Hotspur", "to_league": "Premier League",
        "fee_eur_m": 0, "fee_type": "loan",
        "deal_context": "player_surplus",
        "position": "CF", "transfer_date": "2025-01-24",
        "transfer_window": "2025_jan",
        "notes": "Six-month loan. Needs playing time after limited role at Bayern.",
    },
    {
        "player_name": "Renato Veiga",
        "from_club": "Chelsea", "from_league": "Premier League",
        "to_club": "Juventus", "to_league": "Serie A",
        "fee_eur_m": 0, "fee_type": "loan",
        "deal_context": "player_surplus",
        "position": "CD", "transfer_date": "2025-01-13",
        "transfer_window": "2025_jan",
        "notes": "Versatile defender. Loan with no option to buy.",
    },
    {
        "player_name": "Fikayo Tomori",
        "from_club": "AC Milan", "from_league": "Serie A",
        "to_club": "Juventus", "to_league": "Serie A",
        "fee_eur_m": 0, "fee_type": "loan",
        "deal_context": "club_decision",
        "position": "CD", "transfer_date": "2025-01-28",
        "transfer_window": "2025_jan",
        "notes": "Lost starting spot under Conceição. Juve's third Jan CB loan.",
    },
    {
        "player_name": "Neto",
        "from_club": "Arsenal", "from_league": "Premier League",
        "to_club": "Bournemouth", "to_league": "Premier League",
        "fee_eur_m": 0, "fee_type": "loan",
        "deal_context": "player_surplus",
        "position": "GK", "transfer_date": "2025-01-21",
        "transfer_window": "2025_jan",
        "notes": "Third-choice at Arsenal. Bournemouth needed GK cover.",
    },
    {
        "player_name": "Andriy Lunin",
        "from_club": "Real Madrid", "from_league": "La Liga",
        "to_club": "Majorca", "to_league": "La Liga",
        "fee_eur_m": 0, "fee_type": "loan",
        "deal_context": "player_surplus",
        "position": "GK", "transfer_date": "2025-01-20",
        "transfer_window": "2025_jan",
        "notes": "Courtois back as #1. Lunin needs minutes.",
    },
    {
        "player_name": "Niclas Füllkrug",
        "from_club": "West Ham", "from_league": "Premier League",
        "to_club": "AC Milan", "to_league": "Serie A",
        "fee_eur_m": 0, "fee_type": "loan",
        "deal_context": "player_surplus",
        "position": "CF", "transfer_date": "2025-01-25",
        "transfer_window": "2025_jan",
        "notes": "Injury-plagued spell at West Ham. Milan took chance on fitness.",
    },
    {
        "player_name": "Leroy Sané",
        "from_club": "Bayern Munich", "from_league": "Bundesliga",
        "to_club": "—", "to_league": None,
        "fee_eur_m": 0, "fee_type": "free",
        "deal_context": "contract_expiring",
        "position": "WF", "transfer_date": "2025-01-15",
        "transfer_window": "2025_jan",
        "notes": "Left Bayern as free agent. Exploring options.",
    },
    {
        "player_name": "Ashley Young",
        "from_club": "Everton", "from_league": "Premier League",
        "to_club": "—", "to_league": None,
        "fee_eur_m": 0, "fee_type": "free",
        "deal_context": "contract_expiring",
        "position": "WD", "transfer_date": "2025-01-10",
        "transfer_window": "2025_jan",
        "notes": "Released by Everton. Veteran career winding down.",
    },

    # ── Summer 2025 window ───────────────────────────────────────────────────
    {
        "player_name": "Alexander Isak",
        "from_club": "Newcastle United", "from_league": "Premier League",
        "to_club": "Liverpool", "to_league": "Premier League",
        "fee_eur_m": 150, "fee_type": "permanent",
        "deal_context": "release_clause",
        "position": "CF", "transfer_date": "2025-09-01",
        "transfer_window": "2025_summer",
        "notes": "British record fee. Deadline Day blockbuster. 25 PL goals in 24/25.",
    },
    {
        "player_name": "Florian Wirtz",
        "from_club": "Bayer Leverkusen", "from_league": "Bundesliga",
        "to_club": "Liverpool", "to_league": "Premier League",
        "fee_eur_m": 120, "fee_type": "permanent",
        "deal_context": "release_clause",
        "position": "AM", "transfer_date": "2025-07-15",
        "transfer_window": "2025_summer",
        "notes": "Liverpool's marquee signing. €120m base, up to €140m with add-ons.",
    },
    {
        "player_name": "Hugo Ekitike",
        "from_club": "Eintracht Frankfurt", "from_league": "Bundesliga",
        "to_club": "Liverpool", "to_league": "Premier League",
        "fee_eur_m": 93, "fee_type": "permanent",
        "deal_context": "club_decision",
        "position": "CF", "transfer_date": "2025-08-10",
        "transfer_window": "2025_summer",
        "notes": "Part of Liverpool's aggressive summer rebuild. Up to €93m with add-ons.",
    },
    {
        "player_name": "Bryan Mbeumo",
        "from_club": "Brentford", "from_league": "Premier League",
        "to_club": "Manchester United", "to_league": "Premier League",
        "fee_eur_m": 83, "fee_type": "permanent",
        "deal_context": "club_decision",
        "position": "WF", "transfer_date": "2025-08-05",
        "transfer_window": "2025_summer",
        "notes": "Up to €83m with add-ons. United's headline summer signing.",
    },
    {
        "player_name": "Matheus Cunha",
        "from_club": "Wolverhampton Wanderers", "from_league": "Premier League",
        "to_club": "Manchester United", "to_league": "Premier League",
        "fee_eur_m": 75, "fee_type": "permanent",
        "deal_context": "club_decision",
        "position": "CF", "transfer_date": "2025-07-25",
        "transfer_window": "2025_summer",
        "notes": "United raided Wolves. Cunha's versatility appealed to ten Hag's successor.",
    },
    {
        "player_name": "Eberechi Eze",
        "from_club": "Crystal Palace", "from_league": "Premier League",
        "to_club": "Arsenal", "to_league": "Premier League",
        "fee_eur_m": 70, "fee_type": "permanent",
        "deal_context": "release_clause",
        "position": "AM", "transfer_date": "2025-08-22",
        "transfer_window": "2025_summer",
        "notes": "Release clause expired Aug 15 but Arsenal agreed similar fee. Up to €80m.",
    },
    {
        "player_name": "Martín Zubimendi",
        "from_club": "Real Sociedad", "from_league": "La Liga",
        "to_club": "Arsenal", "to_league": "Premier League",
        "fee_eur_m": 70, "fee_type": "permanent",
        "deal_context": "release_clause",
        "position": "DM", "transfer_date": "2025-07-20",
        "transfer_window": "2025_summer",
        "notes": "Turned down Liverpool in 2024. Chose Arsenal a year later.",
    },
    {
        "player_name": "Victor Osimhen",
        "from_club": "Napoli", "from_league": "Serie A",
        "to_club": "Galatasaray", "to_league": "Süper Lig",
        "fee_eur_m": 75, "fee_type": "permanent",
        "deal_context": "transfer_request",
        "position": "CF", "transfer_date": "2025-07-10",
        "transfer_window": "2025_summer",
        "notes": "Made permanent after successful loan spell. Dominated Turkish league.",
    },
    {
        "player_name": "Luis Díaz",
        "from_club": "Liverpool", "from_league": "Premier League",
        "to_club": "Bayern Munich", "to_league": "Bundesliga",
        "fee_eur_m": 70, "fee_type": "permanent",
        "deal_context": "club_decision",
        "position": "WF", "transfer_date": "2025-08-01",
        "transfer_window": "2025_summer",
        "notes": "Liverpool reinvested Díaz fee into Isak + Ekitike. Bayern got a bargain.",
    },
    {
        "player_name": "Nick Woltemade",
        "from_club": "VfB Stuttgart", "from_league": "Bundesliga",
        "to_club": "Newcastle United", "to_league": "Premier League",
        "fee_eur_m": 75, "fee_type": "permanent",
        "deal_context": "club_decision",
        "position": "CF", "transfer_date": "2025-08-15",
        "transfer_window": "2025_summer",
        "notes": "Newcastle record signing. Standout at U21 Euros.",
    },
    {
        "player_name": "Viktor Gyökeres",
        "from_club": "Sporting CP", "from_league": "Primeira Liga",
        "to_club": "Arsenal", "to_league": "Premier League",
        "fee_eur_m": 65, "fee_type": "permanent",
        "deal_context": "release_clause",
        "position": "CF", "transfer_date": "2025-07-30",
        "transfer_window": "2025_summer",
        "notes": "Arsenal's striker signing. Release clause triggered.",
    },
    {
        "player_name": "Mohammed Kudus",
        "from_club": "West Ham United", "from_league": "Premier League",
        "to_club": "Tottenham Hotspur", "to_league": "Premier League",
        "fee_eur_m": 65, "fee_type": "permanent",
        "deal_context": "club_decision",
        "position": "AM", "transfer_date": "2025-08-12",
        "transfer_window": "2025_summer",
        "notes": "Spurs signed Kudus for €65m after strong two seasons at West Ham.",
    },
    {
        "player_name": "Dean Huijsen",
        "from_club": "AFC Bournemouth", "from_league": "Premier League",
        "to_club": "Real Madrid", "to_league": "La Liga",
        "fee_eur_m": 60, "fee_type": "permanent",
        "deal_context": "release_clause",
        "position": "CD", "transfer_date": "2025-07-05",
        "transfer_window": "2025_summer",
        "notes": "Release clause matched. Bournemouth bought for €15m, sold for €60m in one year.",
    },
    {
        "player_name": "Jobe Bellingham",
        "from_club": "Sunderland", "from_league": "Championship",
        "to_club": "Borussia Dortmund", "to_league": "Bundesliga",
        "fee_eur_m": 38, "fee_type": "permanent",
        "deal_context": "club_decision",
        "position": "CM", "transfer_date": "2025-07-18",
        "transfer_window": "2025_summer",
        "notes": "Follows brother Jude's path to Dortmund. Club record fee for Sunderland.",
    },

    # ── January 2026 window ──────────────────────────────────────────────────
    {
        "player_name": "Antoine Semenyo",
        "from_club": "AFC Bournemouth", "from_league": "Premier League",
        "to_club": "Manchester City", "to_league": "Premier League",
        "fee_eur_m": 72, "fee_type": "permanent",
        "deal_context": "release_clause",
        "position": "WF", "transfer_date": "2026-01-20",
        "transfer_window": "2026_jan",
        "notes": "Most expensive signing of Jan 2026 window. Release clause of £65m.",
    },
    {
        "player_name": "Lucas Paquetá",
        "from_club": "West Ham United", "from_league": "Premier League",
        "to_club": "Flamengo", "to_league": "Brasileirão",
        "fee_eur_m": 42, "fee_type": "permanent",
        "deal_context": "mutual_termination",
        "position": "AM", "transfer_date": "2026-01-25",
        "transfer_window": "2026_jan",
        "notes": "Highest incoming transfer in Brazilian league history. €42m.",
    },
    {
        "player_name": "Conor Gallagher",
        "from_club": "Atlético Madrid", "from_league": "La Liga",
        "to_club": "Tottenham Hotspur", "to_league": "Premier League",
        "fee_eur_m": 40, "fee_type": "permanent",
        "deal_context": "club_decision",
        "position": "CM", "transfer_date": "2026-01-22",
        "transfer_window": "2026_jan",
        "notes": "Spurs won race to bring Gallagher back to PL over Aston Villa.",
    },
    {
        "player_name": "Brennan Johnson",
        "from_club": "Tottenham Hotspur", "from_league": "Premier League",
        "to_club": "Crystal Palace", "to_league": "Premier League",
        "fee_eur_m": 40, "fee_type": "permanent",
        "deal_context": "player_surplus",
        "position": "WF", "transfer_date": "2026-01-05",
        "transfer_window": "2026_jan",
        "notes": "Palace broke their transfer record. Agreed before window even opened.",
    },
    {
        "player_name": "Ademola Lookman",
        "from_club": "Atalanta", "from_league": "Serie A",
        "to_club": "Atlético Madrid", "to_league": "La Liga",
        "fee_eur_m": 35, "fee_type": "permanent",
        "deal_context": "transfer_request",
        "position": "WF", "transfer_date": "2026-02-03",
        "transfer_window": "2026_jan",
        "notes": "Handed in transfer request over summer. Finally left on Deadline Day.",
    },
    {
        "player_name": "Oscar Bobb",
        "from_club": "Manchester City", "from_league": "Premier League",
        "to_club": "Fulham", "to_league": "Premier League",
        "fee_eur_m": 31, "fee_type": "permanent",
        "deal_context": "player_surplus",
        "position": "WF", "transfer_date": "2026-01-28",
        "transfer_window": "2026_jan",
        "notes": "Guardiola allowed departure after Semenyo arrival. €31.2m.",
    },
    {
        "player_name": "Taty Castellanos",
        "from_club": "Lazio", "from_league": "Serie A",
        "to_club": "West Ham United", "to_league": "Premier League",
        "fee_eur_m": 29, "fee_type": "permanent",
        "deal_context": "club_decision",
        "position": "CF", "transfer_date": "2026-01-26",
        "transfer_window": "2026_jan",
        "notes": "West Ham's Paquetá replacement funds partially. €29m from Lazio.",
    },
    {
        "player_name": "Rayan",
        "from_club": "Vasco da Gama", "from_league": "Brasileirão",
        "to_club": "AFC Bournemouth", "to_league": "Premier League",
        "fee_eur_m": 28, "fee_type": "permanent",
        "deal_context": "club_decision",
        "position": "CF", "transfer_date": "2026-01-30",
        "transfer_window": "2026_jan",
        "notes": "Bournemouth reinvested Semenyo fee. €28.5m plus add-ons.",
    },
    {
        "player_name": "Marc Guehi",
        "from_club": "Crystal Palace", "from_league": "Premier League",
        "to_club": "Manchester City", "to_league": "Premier League",
        "fee_eur_m": 23, "fee_type": "permanent",
        "deal_context": "contract_expiring",
        "position": "CD", "transfer_date": "2026-01-15",
        "transfer_window": "2026_jan",
        "notes": "Contract running down. City got him below summer valuation. €23m.",
    },
    {
        "player_name": "Endrick",
        "from_club": "Real Madrid", "from_league": "La Liga",
        "to_club": "Lyon", "to_league": "Ligue 1",
        "fee_eur_m": 0, "fee_type": "loan",
        "deal_context": "player_surplus",
        "position": "CF", "transfer_date": "2026-01-18",
        "transfer_window": "2026_jan",
        "notes": "Only 99 minutes in all comps first half of season. Needs minutes.",
    },
    {
        "player_name": "Oleksandr Zinchenko",
        "from_club": "Arsenal", "from_league": "Premier League",
        "to_club": "Ajax", "to_league": "Eredivisie",
        "fee_eur_m": 1.5, "fee_type": "permanent",
        "deal_context": "player_surplus",
        "position": "WD", "transfer_date": "2026-01-20",
        "transfer_window": "2026_jan",
        "notes": "Arsenal let him go for a token €1.5m. Ajax got a bargain.",
    },
]

# ── People lookup for player_id + archetype matching ─────────────────────────

cur.execute("SELECT id, name, date_of_birth FROM people")
rows = cur.fetchall()
people_lookup = {}
for pid, name, dob in rows:
    people_lookup[name.lower().strip()] = (pid, dob)

# Archetype lookup
cur.execute("SELECT person_id, earned_archetype FROM player_profiles WHERE earned_archetype IS NOT NULL")
archetype_lookup = {}
for person_id, archetype in cur.fetchall():
    archetype_lookup[person_id] = archetype


def compute_age(dob, transfer_date):
    """Compute age at transfer date."""
    if not dob or not transfer_date:
        return None
    if isinstance(transfer_date, str):
        parts = transfer_date.split("-")
        transfer_date = date(int(parts[0]), int(parts[1]), int(parts[2]))
    if isinstance(dob, str):
        parts = dob.split("-")
        dob = date(int(parts[0]), int(parts[1]), int(parts[2]))
    age = transfer_date.year - dob.year
    if (transfer_date.month, transfer_date.day) < (dob.month, dob.day):
        age -= 1
    return age


# ── Seed logic ───────────────────────────────────────────────────────────────

if args.force and not args.dry_run:
    cur.execute("DELETE FROM transfers WHERE source = 'seed'")
    deleted = cur.rowcount
    print(f"FORCE: Cleared {deleted} existing seed transfers")

inserted = 0
updated = 0
skipped = 0
unmatched = []

for t in TRANSFERS:
    # Try to match player
    key = t["player_name"].lower().strip()
    player_id = None
    age_at_transfer = t.get("age_at_transfer")
    primary_archetype = None

    if key in people_lookup:
        player_id, dob = people_lookup[key]
        if not age_at_transfer:
            age_at_transfer = compute_age(dob, t["transfer_date"])
        primary_archetype = archetype_lookup.get(player_id)
    else:
        unmatched.append(t["player_name"])

    if args.dry_run:
        status = "MATCH" if player_id else "NO MATCH"
        age_str = f", age {age_at_transfer}" if age_at_transfer else ""
        arch_str = f", {primary_archetype}" if primary_archetype else ""
        print(f"  [{status}] {t['player_name']} → {t['to_club']} (€{t.get('fee_eur_m', '?')}m{age_str}{arch_str})")
        continue

    # Use different conflict handling based on whether player_id is matched
    if player_id:
        # Matched player: use the matched dedup index
        cur.execute("""
            INSERT INTO transfers (
                player_name, player_id, age_at_transfer, position,
                from_club, from_league, to_club, to_league,
                fee_eur_m, fee_type, deal_context,
                transfer_date, transfer_window, primary_archetype,
                notes, source, confidence
            ) VALUES (
                %s, %s, %s, %s,
                %s, %s, %s, %s,
                %s, %s, %s,
                %s, %s, %s,
                %s, 'seed', 'high'
            )
            ON CONFLICT (player_id, transfer_date, to_club)
                WHERE player_id IS NOT NULL
            DO UPDATE SET
                player_name = EXCLUDED.player_name,
                age_at_transfer = EXCLUDED.age_at_transfer,
                position = EXCLUDED.position,
                from_club = EXCLUDED.from_club,
                from_league = EXCLUDED.from_league,
                to_league = EXCLUDED.to_league,
                fee_eur_m = EXCLUDED.fee_eur_m,
                fee_type = EXCLUDED.fee_type,
                deal_context = EXCLUDED.deal_context,
                transfer_window = EXCLUDED.transfer_window,
                primary_archetype = EXCLUDED.primary_archetype,
                notes = EXCLUDED.notes,
                source = EXCLUDED.source,
                confidence = EXCLUDED.confidence,
                updated_at = now()
        """, (
            t["player_name"], player_id, age_at_transfer, t.get("position"),
            t["from_club"], t.get("from_league"), t["to_club"], t.get("to_league"),
            t.get("fee_eur_m"), t["fee_type"], t.get("deal_context"),
            t["transfer_date"], t.get("transfer_window"), primary_archetype,
            t.get("notes"),
        ))
    else:
        # Unmatched player: use the unmatched dedup index
        cur.execute("""
            INSERT INTO transfers (
                player_name, player_id, age_at_transfer, position,
                from_club, from_league, to_club, to_league,
                fee_eur_m, fee_type, deal_context,
                transfer_date, transfer_window, primary_archetype,
                notes, source, confidence
            ) VALUES (
                %s, NULL, %s, %s,
                %s, %s, %s, %s,
                %s, %s, %s,
                %s, %s, %s,
                %s, 'seed', 'high'
            )
            ON CONFLICT (player_name, transfer_date, to_club)
                WHERE player_id IS NULL
            DO UPDATE SET
                age_at_transfer = EXCLUDED.age_at_transfer,
                position = EXCLUDED.position,
                from_club = EXCLUDED.from_club,
                from_league = EXCLUDED.from_league,
                to_league = EXCLUDED.to_league,
                fee_eur_m = EXCLUDED.fee_eur_m,
                fee_type = EXCLUDED.fee_type,
                deal_context = EXCLUDED.deal_context,
                transfer_window = EXCLUDED.transfer_window,
                primary_archetype = EXCLUDED.primary_archetype,
                notes = EXCLUDED.notes,
                source = EXCLUDED.source,
                confidence = EXCLUDED.confidence,
                updated_at = now()
        """, (
            t["player_name"], age_at_transfer, t.get("position"),
            t["from_club"], t.get("from_league"), t["to_club"], t.get("to_league"),
            t.get("fee_eur_m"), t["fee_type"], t.get("deal_context"),
            t["transfer_date"], t.get("transfer_window"), primary_archetype,
            t.get("notes"),
        ))

    inserted += 1

# ── Summary ──────────────────────────────────────────────────────────────────

if args.dry_run:
    print(f"\nDRY RUN: {len(TRANSFERS)} transfers would be upserted")
    print(f"  Matched: {len(TRANSFERS) - len(unmatched)}")
    print(f"  Unmatched: {len(unmatched)}")
else:
    print(f"\nDone: {inserted} transfers upserted")

if unmatched:
    print(f"\nUnmatched players ({len(unmatched)}):")
    for name in unmatched:
        print(f"  - {name}")

cur.close()
conn.close()
